const AllCountries: { title: string; value: string }[] = [
  { title: 'Netherlands', value: 'NLD' },
  { title: 'United Kingdom', value: 'GBR' },
  { title: 'Germany', value: 'DEU' },
  { title: 'France', value: 'FRA' },
  { title: 'Afghanistan', value: 'AFG' },
  { title: 'Åland Islands', value: 'ALA' },
  { title: 'Albania', value: 'ALB' },
  { title: 'Algeria', value: 'DZA' },
  { title: 'American Samoa', value: 'ASM' },
  { title: 'Andorra', value: 'AND' },
  { title: 'Angola', value: 'AGO' },
  { title: 'Anguilla', value: 'AIA' },
  { title: 'Antarctica', value: 'ATA' },
  { title: 'Antigua and Barbuda', value: 'ATG' },
  { title: 'Argentina', value: 'ARG' },
  { title: 'Armenia', value: 'ARM' },
  { title: 'Aruba', value: 'ABW' },
  { title: 'Australia', value: 'AUS' },
  { title: 'Austria', value: 'AUT' },
  { title: 'Azerbaijan', value: 'AZE' },
  { title: 'Bahamas', value: 'BHS' },
  { title: 'Bahrain', value: 'BHR' },
  { title: 'Bangladesh', value: 'BGD' },
  { title: 'Barbados', value: 'BRB' },
  { title: 'Belarus', value: 'BLR' },
  { title: 'Belgium', value: 'BEL' },
  { title: 'Belize', value: 'BLZ' },
  { title: 'Benin', value: 'BEN' },
  { title: 'Bermuda', value: 'BMU' },
  { title: 'Bhutan', value: 'BTN' },
  { title: 'Bolivia (Plurinational State of)', value: 'BOL' },
  { title: 'Bonaire, Sint Eustatius and Saba', value: 'BES' },
  { title: 'Bosnia and Herzegovina', value: 'BIH' },
  { title: 'Botswana', value: 'BWA' },
  { title: 'Bouvet Island', value: 'BVT' },
  { title: 'Brazil', value: 'BRA' },
  { title: 'British Indian Ocean Territory', value: 'IOT' },
  { title: 'Brunei Darussalam', value: 'BRN' },
  { title: 'Bulgaria', value: 'BGR' },
  { title: 'Burkina Faso', value: 'BFA' },
  { title: 'Burundi', value: 'BDI' },
  { title: 'Cabo Verde', value: 'CPV' },
  { title: 'Cambodia', value: 'KHM' },
  { title: 'Cameroon', value: 'CMR' },
  { title: 'Canada', value: 'CAN' },
  { title: 'Cayman Islands', value: 'CYM' },
  { title: 'Central African Republic', value: 'CAF' },
  { title: 'Chad', value: 'TCD' },
  { title: 'Chile', value: 'CHL' },
  { title: 'China', value: 'CHN' },
  { title: 'Christmas Island', value: 'CXR' },
  { title: 'Cocos (Keeling) Islands', value: 'CCK' },
  { title: 'Colombia', value: 'COL' },
  { title: 'Comoros', value: 'COM' },
  { title: 'Congo', value: 'COG' },
  { title: 'Congo, Democratic Republic of the', value: 'COD' },
  { title: 'Cook Islands', value: 'COK' },
  { title: 'Costa Rica', value: 'CRI' },
  { title: "Côte d'Ivoire", value: 'CIV' },
  { title: 'Croatia', value: 'HRV' },
  { title: 'Cuba', value: 'CUB' },
  { title: 'Curaçao', value: 'CUW' },
  { title: 'Cyprus', value: 'CYP' },
  { title: 'Czechia', value: 'CZE' },
  { title: 'Denmark', value: 'DNK' },
  { title: 'Djibouti', value: 'DJI' },
  { title: 'Dominica', value: 'DMA' },
  { title: 'Dominican Republic', value: 'DOM' },
  { title: 'Ecuador', value: 'ECU' },
  { title: 'Egypt', value: 'EGY' },
  { title: 'El Salvador', value: 'SLV' },
  { title: 'Equatorial Guinea', value: 'GNQ' },
  { title: 'Eritrea', value: 'ERI' },
  { title: 'Estonia', value: 'EST' },
  { title: 'Eswatini', value: 'SWZ' },
  { title: 'Ethiopia', value: 'ETH' },
  { title: 'Falkland Islands (Malvinas)', value: 'FLK' },
  { title: 'Faroe Islands', value: 'FRO' },
  { title: 'Fiji', value: 'FJI' },
  { title: 'Finland', value: 'FIN' },
  { title: 'French Guiana', value: 'GUF' },
  { title: 'French Polynesia', value: 'PYF' },
  { title: 'French Southern Territories', value: 'ATF' },
  { title: 'Gabon', value: 'GAB' },
  { title: 'Gambia', value: 'GMB' },
  { title: 'Georgia', value: 'GEO' },
  { title: 'Ghana', value: 'GHA' },
  { title: 'Gibraltar', value: 'GIB' },
  { title: 'Greece', value: 'GRC' },
  { title: 'Greenland', value: 'GRL' },
  { title: 'Grenada', value: 'GRD' },
  { title: 'Guadeloupe', value: 'GLP' },
  { title: 'Guam', value: 'GUM' },
  { title: 'Guatemala', value: 'GTM' },
  { title: 'Guernsey', value: 'GGY' },
  { title: 'Guinea', value: 'GIN' },
  { title: 'Guinea-Bissau', value: 'GNB' },
  { title: 'Guyana', value: 'GUY' },
  { title: 'Haiti', value: 'HTI' },
  { title: 'Heard Island and McDonald Islands', value: 'HMD' },
  { title: 'Holy See', value: 'VAT' },
  { title: 'Honduras', value: 'HND' },
  { title: 'Hong Kong', value: 'HKG' },
  { title: 'Hungary', value: 'HUN' },
  { title: 'Iceland', value: 'ISL' },
  { title: 'India', value: 'IND' },
  { title: 'Indonesia', value: 'IDN' },
  { title: 'Iran (Islamic Republic of)', value: 'IRN' },
  { title: 'Iraq', value: 'IRQ' },
  { title: 'Ireland', value: 'IRL' },
  { title: 'Isle of Man', value: 'IMN' },
  { title: 'Israel', value: 'ISR' },
  { title: 'Italy', value: 'ITA' },
  { title: 'Jamaica', value: 'JAM' },
  { title: 'Japan', value: 'JPN' },
  { title: 'Jersey', value: 'JEY' },
  { title: 'Jordan', value: 'JOR' },
  { title: 'Kazakhstan', value: 'KAZ' },
  { title: 'Kenya', value: 'KEN' },
  { title: 'Kiribati', value: 'KIR' },
  { title: "Korea (Democratic People's Republic of)", value: 'PRK' },
  { title: 'Korea, Republic of', value: 'KOR' },
  { title: 'Kuwait', value: 'KWT' },
  { title: 'Kyrgyzstan', value: 'KGZ' },
  { title: "Lao People's Democratic Republic", value: 'LAO' },
  { title: 'Latvia', value: 'LVA' },
  { title: 'Lebanon', value: 'LBN' },
  { title: 'Lesotho', value: 'LSO' },
  { title: 'Liberia', value: 'LBR' },
  { title: 'Libya', value: 'LBY' },
  { title: 'Liechtenstein', value: 'LIE' },
  { title: 'Lithuania', value: 'LTU' },
  { title: 'Luxembourg', value: 'LUX' },
  { title: 'Macao', value: 'MAC' },
  { title: 'Madagascar', value: 'MDG' },
  { title: 'Malawi', value: 'MWI' },
  { title: 'Malaysia', value: 'MYS' },
  { title: 'Maldives', value: 'MDV' },
  { title: 'Mali', value: 'MLI' },
  { title: 'Malta', value: 'MLT' },
  { title: 'Marshall Islands', value: 'MHL' },
  { title: 'Martinique', value: 'MTQ' },
  { title: 'Mauritania', value: 'MRT' },
  { title: 'Mauritius', value: 'MUS' },
  { title: 'Mayotte', value: 'MYT' },
  { title: 'Mexico', value: 'MEX' },
  { title: 'Micronesia (Federated States of)', value: 'FSM' },
  { title: 'Moldova, Republic of', value: 'MDA' },
  { title: 'Monaco', value: 'MCO' },
  { title: 'Mongolia', value: 'MNG' },
  { title: 'Montenegro', value: 'MNE' },
  { title: 'Montserrat', value: 'MSR' },
  { title: 'Morocco', value: 'MAR' },
  { title: 'Mozambique', value: 'MOZ' },
  { title: 'Myanmar', value: 'MMR' },
  { title: 'Namibia', value: 'NAM' },
  { title: 'Nauru', value: 'NRU' },
  { title: 'Nepal', value: 'NPL' },
  { title: 'New Caledonia', value: 'NCL' },
  { title: 'New Zealand', value: 'NZL' },
  { title: 'Nicaragua', value: 'NIC' },
  { title: 'Niger', value: 'NER' },
  { title: 'Nigeria', value: 'NGA' },
  { title: 'Niue', value: 'NIU' },
  { title: 'Norfolk Island', value: 'NFK' },
  { title: 'North Macedonia', value: 'MKD' },
  { title: 'Northern Mariana Islands', value: 'MNP' },
  { title: 'Norway', value: 'NOR' },
  { title: 'Oman', value: 'OMN' },
  { title: 'Pakistan', value: 'PAK' },
  { title: 'Palau', value: 'PLW' },
  { title: 'Palestine, State of', value: 'PSE' },
  { title: 'Panama', value: 'PAN' },
  { title: 'Papua New Guinea', value: 'PNG' },
  { title: 'Paraguay', value: 'PRY' },
  { title: 'Peru', value: 'PER' },
  { title: 'Philippines', value: 'PHL' },
  { title: 'Pitcairn', value: 'PCN' },
  { title: 'Poland', value: 'POL' },
  { title: 'Portugal', value: 'PRT' },
  { title: 'Puerto Rico', value: 'PRI' },
  { title: 'Qatar', value: 'QAT' },
  { title: 'Réunion', value: 'REU' },
  { title: 'Romania', value: 'ROU' },
  { title: 'Russian Federation', value: 'RUS' },
  { title: 'Rwanda', value: 'RWA' },
  { title: 'Saint Barthélemy', value: 'BLM' },
  { title: 'Saint Helena, Ascension and Tristan da Cunha', value: 'SHN' },
  { title: 'Saint Kitts and Nevis', value: 'KNA' },
  { title: 'Saint Lucia', value: 'LCA' },
  { title: 'Saint Martin (French part)', value: 'MAF' },
  { title: 'Saint Pierre and Miquelon', value: 'SPM' },
  { title: 'Saint Vincent and the Grenadines', value: 'VCT' },
  { title: 'Samoa', value: 'WSM' },
  { title: 'San Marino', value: 'SMR' },
  { title: 'Sao Tome and Principe', value: 'STP' },
  { title: 'Saudi Arabia', value: 'SAU' },
  { title: 'Senegal', value: 'SEN' },
  { title: 'Serbia', value: 'SRB' },
  { title: 'Seychelles', value: 'SYC' },
  { title: 'Sierra Leone', value: 'SLE' },
  { title: 'Singapore', value: 'SGP' },
  { title: 'Sint Maarten (Dutch part)', value: 'SXM' },
  { title: 'Slovakia', value: 'SVK' },
  { title: 'Slovenia', value: 'SVN' },
  { title: 'Solomon Islands', value: 'SLB' },
  { title: 'Somalia', value: 'SOM' },
  { title: 'South Africa', value: 'ZAF' },
  { title: 'South Georgia and the South Sandwich Islands', value: 'SGS' },
  { title: 'South Sudan', value: 'SSD' },
  { title: 'Spain', value: 'ESP' },
  { title: 'Sri Lanka', value: 'LKA' },
  { title: 'Sudan', value: 'SDN' },
  { title: 'Surititle', value: 'SUR' },
  { title: 'Svalbard and Jan Mayen', value: 'SJM' },
  { title: 'Sweden', value: 'SWE' },
  { title: 'Switzerland', value: 'CHE' },
  { title: 'Syrian Arab Republic', value: 'SYR' },
  { title: 'Taiwan, Province of China', value: 'TWN' },
  { title: 'Tajikistan', value: 'TJK' },
  { title: 'Tanzania, United Republic of', value: 'TZA' },
  { title: 'Thailand', value: 'THA' },
  { title: 'Timor-Leste', value: 'TLS' },
  { title: 'Togo', value: 'TGO' },
  { title: 'Tokelau', value: 'TKL' },
  { title: 'Tonga', value: 'TON' },
  { title: 'Trinidad and Tobago', value: 'TTO' },
  { title: 'Tunisia', value: 'TUN' },
  { title: 'Turkey', value: 'TUR' },
  { title: 'Turkmenistan', value: 'TKM' },
  { title: 'Turks and Caicos Islands', value: 'TCA' },
  { title: 'Tuvalu', value: 'TUV' },
  { title: 'Uganda', value: 'UGA' },
  { title: 'Ukraine', value: 'UKR' },
  { title: 'United Arab Emirates', value: 'ARE' },
  { title: 'United States of America', value: 'USA' },
  { title: 'United States Minor Outlying Islands', value: 'UMI' },
  { title: 'Uruguay', value: 'URY' },
  { title: 'Uzbekistan', value: 'UZB' },
  { title: 'Vanuatu', value: 'VUT' },
  { title: 'Venezuela (Bolivarian Republic of)', value: 'VEN' },
  { title: 'Viet Nam', value: 'VNM' },
  { title: 'Virgin Islands (British)', value: 'VGB' },
  { title: 'Virgin Islands (U.S.)', value: 'VIR' },
  { title: 'Wallis and Futuna', value: 'WLF' },
  { title: 'Western Sahara', value: 'ESH' },
  { title: 'Yemen', value: 'YEM' },
  { title: 'Zambia', value: 'ZMB' },
  { title: 'Zimbabwe', value: 'ZWE' },
];

export default AllCountries;
